const OpenAI = require('openai');

// Initialize OpenAI client only if API key is available
let openai = null;
if (process.env.OPENAI_API_KEY) {
  openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY
  });
}

/**
 * Break down a task into subtasks using AI
 */
async function breakdownTask(taskDescription, estimatedHours = null) {
  // If OpenAI is not configured, use fallback
  if (!openai) {
    return generateFallbackBreakdown(taskDescription, estimatedHours);
  }

  try {
    const prompt = `You are a productivity assistant. Break down the following task into smaller, actionable subtasks.

Task: "${taskDescription}"
${estimatedHours ? `Total estimated time: ${estimatedHours} hours` : ''}

Provide a JSON response with the following structure:
{
  "mainTask": "cleaned up version of the task title",
  "subtasks": [
    {
      "title": "subtask title",
      "estimatedMinutes": number,
      "order": number starting from 1,
      "tips": "optional helpful tip for this subtask"
    }
  ],
  "totalEstimatedMinutes": total minutes for all subtasks,
  "suggestions": "any additional suggestions for completing this task effectively"
}

Keep subtasks specific and actionable. Aim for 3-7 subtasks depending on complexity.`;

    const completion = await openai.chat.completions.create({
      model: 'gpt-3.5-turbo',
      messages: [
        {
          role: 'system',
          content: 'You are a helpful productivity assistant that breaks down tasks into manageable subtasks. Always respond with valid JSON.'
        },
        {
          role: 'user',
          content: prompt
        }
      ],
      temperature: 0.7,
      max_tokens: 1000
    });

    const responseText = completion.choices[0].message.content;
    
    // Parse JSON from response
    const jsonMatch = responseText.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      throw new Error('Failed to parse AI response');
    }

    const breakdown = JSON.parse(jsonMatch[0]);
    
    return {
      success: true,
      ...breakdown
    };
  } catch (error) {
    console.error('AI breakdown error:', error);
    
    // Fallback to rule-based breakdown
    return fallbackBreakdown(taskDescription, estimatedHours);
  }
}

/**
 * Fallback rule-based task breakdown when AI is unavailable
 */
function fallbackBreakdown(taskDescription, estimatedHours) {
  const totalMinutes = estimatedHours ? estimatedHours * 60 : 120;
  const lowerTask = taskDescription.toLowerCase();

  // Common task patterns
  const patterns = {
    study: [
      { title: 'Review notes and materials', ratio: 0.25 },
      { title: 'Create summary/outline', ratio: 0.15 },
      { title: 'Practice exercises/problems', ratio: 0.35 },
      { title: 'Review and test yourself', ratio: 0.25 }
    ],
    exam: [
      { title: 'Review lecture notes', ratio: 0.2 },
      { title: 'Review key concepts and definitions', ratio: 0.15 },
      { title: 'Practice with past papers/questions', ratio: 0.35 },
      { title: 'Create cheat sheet/summary', ratio: 0.15 },
      { title: 'Final review and rest', ratio: 0.15 }
    ],
    project: [
      { title: 'Define scope and requirements', ratio: 0.15 },
      { title: 'Research and gather resources', ratio: 0.2 },
      { title: 'Create outline/plan', ratio: 0.1 },
      { title: 'Execute main work', ratio: 0.4 },
      { title: 'Review and refine', ratio: 0.15 }
    ],
    report: [
      { title: 'Research and gather information', ratio: 0.25 },
      { title: 'Create outline', ratio: 0.1 },
      { title: 'Write first draft', ratio: 0.35 },
      { title: 'Edit and proofread', ratio: 0.2 },
      { title: 'Format and finalize', ratio: 0.1 }
    ],
    default: [
      { title: 'Plan and prepare', ratio: 0.15 },
      { title: 'Main work - Part 1', ratio: 0.35 },
      { title: 'Main work - Part 2', ratio: 0.35 },
      { title: 'Review and complete', ratio: 0.15 }
    ]
  };

  // Determine which pattern to use
  let template = patterns.default;
  if (lowerTask.includes('exam') || lowerTask.includes('test')) {
    template = patterns.exam;
  } else if (lowerTask.includes('study') || lowerTask.includes('learn')) {
    template = patterns.study;
  } else if (lowerTask.includes('project')) {
    template = patterns.project;
  } else if (lowerTask.includes('report') || lowerTask.includes('essay') || lowerTask.includes('write')) {
    template = patterns.report;
  }

  const subtasks = template.map((item, index) => ({
    title: item.title,
    estimatedMinutes: Math.round(totalMinutes * item.ratio),
    order: index + 1
  }));

  return {
    success: true,
    mainTask: taskDescription,
    subtasks,
    totalEstimatedMinutes: totalMinutes,
    suggestions: 'This is an automated breakdown. Feel free to adjust the subtasks and time estimates based on your needs.',
    isAutoGenerated: true
  };
}

module.exports = {
  breakdownTask
};
